# Generated by Django 5.2.8 on 2025-11-14 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 19, 59, 13, 517364, tzinfo=datetime.timezone.utc)),
        ),
    ]
