# Generated by Django 5.2.8 on 2025-11-14 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 21, 53, 41, 82217, tzinfo=datetime.timezone.utc)),
        ),
    ]
