# Generated by Django 5.2.8 on 2025-11-14 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 23, 11, 58, 751158, tzinfo=datetime.timezone.utc)),
        ),
    ]
