# Generated by Django 5.2.8 on 2025-11-15 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_test_end_date_checktest_checkquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktest',
            old_name='finded_question',
            new_name='finded_questions',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 9, 8, 57, 525622, tzinfo=datetime.timezone.utc)),
        ),
    ]
