# Generated by Django 5.2.8 on 2025-11-15 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_finded_question_checktest_finded_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 9, 25, 4, 752187, tzinfo=datetime.timezone.utc)),
        ),
    ]
