# Generated by Django 5.2.8 on 2025-11-15 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='true_answer',
            field=models.CharField(help_text='Enter the correct option (a/b/c/d)', max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 9, 28, 32, 27551, tzinfo=datetime.timezone.utc)),
        ),
    ]
