# Generated by Django 5.2.8 on 2025-11-15 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 9, 57, 43, 944493, tzinfo=datetime.timezone.utc)),
        ),
    ]
