# Generated by Django 5.2.8 on 2025-11-15 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 19, 58, 41, 87660, tzinfo=datetime.timezone.utc)),
        ),
    ]
