# Generated by Django 5.2.8 on 2025-12-15 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_checktest_is_public_alter_test_end_date_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.AddField(
            model_name='checktest',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checktest',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 15, 20, 27, 6, 435875, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Test davomiyligi (daqiqada)'),
        ),
    ]
