# Generated by Django 5.2.8 on 2026-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_count',
            field=models.PositiveIntegerField(default=0, help_text='Nechta savol tushishi (0 - barchasi)'),
        ),
    ]
